### ISSUE TITLE
Cannot find module 'socket.io-client/build/typed-events' or its corresponding type declarations.

### ISSUE THREAD

**Issue by matthewclickbid** [millicast/millicast-spaces-app#1]
When using "ionic serve" it does not locate 'socket.io-client/build/typed-events' in node_modules. 

- Downloaded repo
- Opened folder in Visual Studio
- Ran npm i
- Ran ionic serve
- Received error
![Screenshot 2021-12-16 105406](https://user-images.githubusercontent.com/11916448/146404849-cd4a470a-f0d6-4b65-9fc4-524443ad017f.png)

**Comment by murillo128** [comment]
should be working now, please update and try again
